// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDmNtcl8PDhSNHCdR4VSlKTup8ZiRbuKPc',
    appId: '1:829663782203:web:36b50e8dbb2a3d3822431e',
    messagingSenderId: '829663782203',
    projectId: 'bear-board',
    authDomain: 'bear-board.firebaseapp.com',
    storageBucket: 'bear-board.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBXuF653Byy2ghEWX1OZ5-aODT72ns9jmc',
    appId: '1:829663782203:android:5f0fdd1c2e16ee2d22431e',
    messagingSenderId: '829663782203',
    projectId: 'bear-board',
    storageBucket: 'bear-board.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBpcc_0NnSwU3qSkDpkm7HndK6KYr_HBQE',
    appId: '1:829663782203:ios:88d192f37e895b7d22431e',
    messagingSenderId: '829663782203',
    projectId: 'bear-board',
    storageBucket: 'bear-board.appspot.com',
    androidClientId: '829663782203-727mj6cqog1vrqjr3esd819busnaohgu.apps.googleusercontent.com',
    iosClientId: '829663782203-38oscr5fqfa7s85mhmiolrgbna7jrkpf.apps.googleusercontent.com',
    iosBundleId: 'com.example.theBearBoard',
  );
}
